site_name: Windinator Documentation
site_url: https://gameobject.xyz/windinator
markdown_extensions:
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - codehilite
theme: material
nav:
    - Introduction: index.md
    - Extra UI:
        - UI Graphics: extra-ui.md
        - Material UI: material-ui.md
    - Windows: windows.md
    - Elements: elements.md
    - Classes:
        - Windinator: windinator-class.md
        - Layout: windinator-class.md
        - MaterialUI: windinator-class.md