site_name: Windinator Documentation
site_url: https://gameobject.xyz/windinator
markdown_extensions:
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - codehilite
theme: material
nav:
    - Introduction: index.md
    - Windows: windinator-class.md
    - Elements: windinator-class.md
    - Quick Start: windinator-class.md
    - Classes:
        - Windinator: windinator-class.md